name: BrowserStack

on:
  pull_request:
    branches:
      - main

jobs:
  browserstack:
    runs-on: ubuntu-latest
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install packages
        run: npm ci
      - name: Upload app to BrowserStack
        id: upload-app
        run: |
          res=$(curl -u "$BROWSERSTACK_USERNAME:$BROWSERSTACK_ACCESS_KEY" \
          -X POST "https://api-cloud.browserstack.com/app-automate/upload" \
          -F "file=@apps/wikipedia.apk" | sed -n 's|.*"app_url": *"\([^"]*\)".*|\1|p' \
          -F "custom_id=WikiApp")
          echo $BS_APP_ID
          echo $BS_APP_ID=$res >> GITHUB_OUTPUT

      - name: Run tests on BrowserStack
        run: echo $BS_APP_ID
        env:
          BS_APP_ID: ${{ steps.upload-app.outputs.BS_APP_ID }}
